/**
 * Audit actions and resources, as plain data so client pages (filters) can
 * use them without pulling in the database layer.
 */
export const AUDIT_ACTIONS = [
  "user.login",
  "user.login_failed",
  "user.logout",
  "user.created",
  "user.invited",
  "user.role_changed",
  "user.removed",
  "project.created",
  "project.updated",
  "project.deleted",
  "scan.queued",
  "scan.cancelled",
  "scan.paused",
  "scan.resumed",
  "scan.rescanned",
  "scan.stopped",
  "scan.deleted",
  "scan.uploads_purged",
  "scan.history_purged",
  "scan.old_scans_purged",
  "scan.purge_failed",
  "finding.status_changed",
  "finding.suggest_fix",
  "finding.open_pr",
  "finding.ticket_raised",
  "remediation.started",
  "remediation.cancelled",
  "remediation.pr_opened",
  "buildgate.updated",
  "policy.created",
  "policy.updated",
  "policy.deleted",
  "suppression.created",
  "suppression.updated",
  "suppression.deleted",
  "integration.created",
  "integration.updated",
  "integration.deleted",
  "integration.tested",
  "apikey.created",
  "apikey.revoked",
  "settings.updated",
  "settings.llm.updated",
  "settings.signing.updated",
  "settings.webhooks.updated",
  "settings.audit.updated",
  "audit.exported",
  "audit.purged",
  "audit.purge_failed",
] as const;

export const AUDIT_RESOURCES = [
  "user",
  "project",
  "scan",
  "finding",
  "buildgate",
  "policy",
  "integration",
  "apikey",
  "settings",
  "suppression",
  "audit",
  "organization",
] as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[number];
export type AuditResource = (typeof AUDIT_RESOURCES)[number];
