import type { SecretPattern } from "@/scanners/types";

export const SECRET_PATTERNS: SecretPattern[] = [
  {
    id: "AWS_ACCESS_KEY",
    title: "AWS Access Key ID",
    description:
      "AWS Access Key ID found in code. This can be used to access AWS services.",
    severity: "CRITICAL",
    pattern: /AKIA[0-9A-Z]{16}/,
    allowlist: [/example/i, /test/i, /dummy/i, /fake/i, /placeholder/i],
  },
  {
    id: "AWS_SECRET_KEY",
    title: "AWS Secret Access Key",
    description: "AWS Secret Access Key found in code.",
    severity: "CRITICAL",
    pattern:
      /(?:aws_secret_access_key|AWS_SECRET_ACCESS_KEY|aws_secret)\s*[:=]\s*['"]?[A-Za-z0-9/+=]{40}['"]?/,
  },
  {
    id: "GITHUB_TOKEN",
    title: "GitHub Personal Access Token",
    description:
      "GitHub token found in code. Can be used to access GitHub APIs.",
    severity: "HIGH",
    pattern: /gh[ps]_[A-Za-z0-9_]{36,}/,
  },
  {
    id: "GITHUB_FINE_GRAINED",
    title: "GitHub Fine-Grained Token",
    description: "GitHub fine-grained personal access token found in code.",
    severity: "HIGH",
    pattern: /github_pat_[A-Za-z0-9_]{22,}/,
  },
  {
    id: "GITLAB_TOKEN",
    title: "GitLab Token",
    description: "GitLab personal or project access token found in code.",
    severity: "HIGH",
    pattern: /glpat-[A-Za-z0-9_-]{20,}/,
  },
  {
    id: "SLACK_TOKEN",
    title: "Slack Token",
    description: "Slack bot or user token found in code.",
    severity: "HIGH",
    pattern: /xox[bpors]-[0-9]{10,13}-[0-9]{10,13}-[a-zA-Z0-9]{24,34}/,
  },
  {
    id: "SLACK_WEBHOOK",
    title: "Slack Webhook URL",
    description: "Slack incoming webhook URL found in code.",
    severity: "MEDIUM",
    pattern:
      /https:\/\/hooks\.slack\.com\/services\/T[A-Z0-9]+\/B[A-Z0-9]+\/[a-zA-Z0-9]+/,
  },
  {
    id: "PRIVATE_KEY",
    title: "Private Key",
    description: "Private cryptographic key found in code.",
    severity: "CRITICAL",
    pattern: /-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----/,
  },
  {
    id: "GENERIC_API_KEY",
    title: "Generic API Key",
    description: "Possible API key detected based on variable naming pattern.",
    severity: "MEDIUM",
    pattern:
      /(?:api[_-]?key|apikey|api[_-]?secret|api[_-]?token)\s*[:=]\s*['"][A-Za-z0-9_\-/.+=]{20,}['"]/i,
    allowlist: [
      /example/i,
      /your[_-]?api/i,
      /\$\{/i,
      /process\.env/i,
      /os\.environ/i,
      /ENV\[/i,
    ],
  },
  {
    id: "GENERIC_SECRET",
    title: "Generic Secret",
    description:
      "Possible secret or password detected based on variable naming pattern.",
    severity: "MEDIUM",
    pattern:
      /(?:secret|password|passwd|pwd|token|auth[_-]?key)\s*[:=]\s*['"][A-Za-z0-9_\-/.+=!@#$%^&*]{8,}['"]/i,
    allowlist: [
      /example/i,
      /changeme/i,
      /\$\{/i,
      /process\.env/i,
      /os\.environ/i,
      /placeholder/i,
      /your[_-]/i,
    ],
  },
  {
    id: "JWT_TOKEN",
    title: "JWT Token",
    description: "JSON Web Token found hardcoded in source code.",
    severity: "HIGH",
    pattern: /eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}/,
    allowlist: [/test/i, /example/i, /mock/i],
  },
  {
    id: "GOOGLE_API_KEY",
    title: "Google API Key",
    description: "Google API key found in code.",
    severity: "HIGH",
    pattern: /AIza[0-9A-Za-z_-]{35}/,
  },
  {
    id: "STRIPE_SECRET_KEY",
    title: "Stripe Secret Key",
    description: "Stripe secret API key found in code.",
    severity: "CRITICAL",
    pattern: /sk_live_[0-9a-zA-Z]{24,}/,
  },
  {
    id: "STRIPE_PUBLISHABLE_KEY",
    title: "Stripe Publishable Key",
    description:
      "Stripe publishable key found in code. While not as sensitive as secret keys, it should not be hardcoded.",
    severity: "LOW",
    pattern: /pk_live_[0-9a-zA-Z]{24,}/,
  },
  {
    id: "SENDGRID_API_KEY",
    title: "SendGrid API Key",
    description: "SendGrid API key found in code.",
    severity: "HIGH",
    pattern: /SG\.[A-Za-z0-9_-]{22,}\.[A-Za-z0-9_-]{22,}/,
  },
  {
    id: "TWILIO_API_KEY",
    title: "Twilio API Key",
    description: "Twilio API key or auth token found in code.",
    severity: "HIGH",
    pattern: /SK[0-9a-fA-F]{32}/,
  },
  {
    id: "MAILGUN_KEY",
    title: "Mailgun API Key",
    description: "Mailgun API key found in code.",
    severity: "HIGH",
    pattern: /key-[0-9a-zA-Z]{32}/,
  },
  {
    id: "DATABASE_URL",
    title: "Database Connection String",
    description: "Database connection string with credentials found in code.",
    severity: "HIGH",
    pattern:
      /(?:postgres|mysql|mongodb|redis|amqp):\/\/[^:\s]+:[^@\s]+@[^\s'"]+/,
    allowlist: [/localhost/i, /127\.0\.0\.1/, /example\.com/i],
  },
  {
    id: "HEROKU_API_KEY",
    title: "Heroku API Key",
    description: "Heroku API key found in code.",
    severity: "HIGH",
    pattern:
      /(?:heroku_api_key|HEROKU_API_KEY)\s*[:=]\s*['"]?[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}['"]?/,
  },
  {
    id: "NPM_TOKEN",
    title: "npm Auth Token",
    description: "npm authentication token found in code.",
    severity: "HIGH",
    pattern: /\/\/registry\.npmjs\.org\/:_authToken=[A-Za-z0-9_-]+/,
  },
  {
    id: "AZURE_CONNECTION_STRING",
    title: "Azure Storage Connection String",
    description: "Azure storage connection string found in code.",
    severity: "HIGH",
    pattern:
      /DefaultEndpointsProtocol=https?;AccountName=[^;]+;AccountKey=[A-Za-z0-9/+=]+/,
  },
  {
    id: "OPENAI_API_KEY",
    title: "OpenAI API Key",
    description:
      "OpenAI API key found in code. Can be used to access GPT and other OpenAI services.",
    severity: "HIGH",
    pattern: /sk-[A-Za-z0-9]{20,}T3BlbkFJ[A-Za-z0-9]{20,}/,
  },
  {
    id: "OPENAI_PROJECT_KEY",
    title: "OpenAI Project API Key",
    description: "OpenAI project-scoped API key found in code.",
    severity: "HIGH",
    pattern: /sk-proj-[A-Za-z0-9_-]{40,}/,
  },
  {
    id: "DISCORD_BOT_TOKEN",
    title: "Discord Bot Token",
    description: "Discord bot token found in code. Grants full bot access.",
    severity: "HIGH",
    pattern: /[MN][A-Za-z\d]{23,}\.[\w-]{6}\.[\w-]{27,}/,
    allowlist: [/example/i, /test/i],
  },
  {
    id: "DISCORD_WEBHOOK",
    title: "Discord Webhook URL",
    description: "Discord webhook URL found in code.",
    severity: "MEDIUM",
    pattern:
      /https:\/\/discord(?:app)?\.com\/api\/webhooks\/\d+\/[A-Za-z0-9_-]+/,
  },
  {
    id: "OAUTH_CLIENT_SECRET",
    title: "OAuth Client Secret",
    description:
      "OAuth client_secret found in code. This enables impersonation of the application.",
    severity: "HIGH",
    pattern:
      /(?:client_secret|CLIENT_SECRET|clientSecret)\s*[:=]\s*['"][A-Za-z0-9_\-]{20,}['"]/,
    allowlist: [
      /example/i,
      /\$\{/i,
      /process\.env/i,
      /os\.environ/i,
      /getenv/i,
      /placeholder/i,
    ],
  },
  {
    id: "AZURE_CLIENT_SECRET",
    title: "Azure AD Client Secret",
    description: "Azure Active Directory client secret found in code.",
    severity: "HIGH",
    pattern:
      /(?:AZURE_CLIENT_SECRET|azure_client_secret)\s*[:=]\s*['"][A-Za-z0-9_~.-]{30,}['"]/,
  },
  {
    id: "GCP_SERVICE_ACCOUNT",
    title: "GCP Service Account Key",
    description: "Google Cloud service account private key ID found in code.",
    severity: "CRITICAL",
    pattern: /"private_key_id"\s*:\s*"[a-f0-9]{40}"/,
  },
  {
    id: "DIGITALOCEAN_TOKEN",
    title: "DigitalOcean Access Token",
    description: "DigitalOcean personal access token found in code.",
    severity: "HIGH",
    pattern: /dop_v1_[a-f0-9]{64}/,
  },
  {
    id: "SHOPIFY_TOKEN",
    title: "Shopify Access Token",
    description: "Shopify API access token found in code.",
    severity: "HIGH",
    pattern: /shpat_[a-fA-F0-9]{32}/,
  },
  {
    id: "PYPI_TOKEN",
    title: "PyPI API Token",
    description: "PyPI upload token found in code.",
    severity: "HIGH",
    pattern: /pypi-[A-Za-z0-9_-]{50,}/,
  },
  {
    id: "DOCKER_AUTH",
    title: "Docker Registry Auth",
    description: "Docker registry authentication credentials found in code.",
    severity: "HIGH",
    pattern: /"auth"\s*:\s*"[A-Za-z0-9+/=]{20,}"/,
    allowlist: [/schema/i, /example/i],
  },
  {
    id: "HARDCODED_PASSWORD",
    title: "Hardcoded Password in Assignment",
    description:
      "A password value is hardcoded in source code. Use environment variables or a secrets vault instead.",
    severity: "HIGH",
    pattern: /(?:password|passwd|pwd)\s*[:=]\s*['"][^'"${\s]{4,}['"]/i,
    allowlist: [
      /example/i,
      /changeme/i,
      /placeholder/i,
      /\$\{/i,
      /process\.env/i,
      /os\.environ/i,
      /getenv/i,
      /test/i,
      /password_hash/i,
      /prompt/i,
      /input/i,
    ],
  },
  {
    id: "HARDCODED_CONN_STRING",
    title: "Connection String with Embedded Credentials",
    description:
      "A connection string with embedded username and password was found. Use environment variables for credentials.",
    severity: "HIGH",
    pattern:
      /['"](?:jdbc|Data Source|Server=|Host=).*(?:password|pwd)\s*=\s*[^;'"]+/i,
    allowlist: [/localhost/i, /127\.0\.0\.1/, /example/i],
  },
  {
    id: "SSH_PRIVATE_KEY",
    title: "SSH Private Key",
    description: "SSH private key found in code. This grants access to SSH-protected systems.",
    severity: "CRITICAL",
    pattern: /-----BEGIN (RSA|DSA|EC|OPENSSH|PGP) PRIVATE KEY/,
  },
  {
    id: "JENKINS_CREDENTIALS",
    title: "Jenkins Credentials",
    description: "Jenkins API token or credentials found in code.",
    severity: "HIGH",
    pattern: /(?:JENKINS_API_TOKEN|jenkins_token)\s*[:=]\s*['"][A-Za-z0-9]{20,}['"]/i,
  },
  {
    id: "ARTIFACTORY_TOKEN",
    title: "Artifactory API Token",
    description: "Artifactory API token found in code.",
    severity: "HIGH",
    pattern: /(?:artifactory_token|artifactory_api_key)\s*[:=]\s*['"][A-Za-z0-9]{20,}['"]/i,
  },
  {
    id: "CIRCLECI_TOKEN",
    title: "CircleCI API Token",
    description: "CircleCI API token found in code.",
    severity: "HIGH",
    pattern: /(?:circle_token|circleci_token)\s*[:=]\s*['"][a-f0-9]{40}['"]/i,
  },
  {
    id: "TRAVIS_CI_TOKEN",
    title: "Travis CI API Token",
    description: "Travis CI API token found in code.",
    severity: "HIGH",
    pattern: /(?:travis_token|TRAVIS_TOKEN)\s*[:=]\s*['"][A-Za-z0-9-]{30,}['"]/i,
  },
  {
    id: "CODECOV_TOKEN",
    title: "Codecov API Token",
    description: "Codecov API token found in code.",
    severity: "MEDIUM",
    pattern: /(?:codecov_token|CODECOV_TOKEN)\s*[:=]\s*['"][a-z0-9-]{20,}['"]/i,
  },
  {
    id: "DATADOG_API_KEY",
    title: "Datadog API Key",
    description: "Datadog API key found in code.",
    severity: "HIGH",
    pattern: /(?:datadog_api_key|DD_API_KEY)\s*[:=]\s*['"][a-f0-9]{32}['"]/i,
  },
  {
    id: "NEW_RELIC_API_KEY",
    title: "New Relic API Key",
    description: "New Relic API key found in code.",
    severity: "HIGH",
    pattern: /(?:new_relic_api_key|NRAPI-[a-zA-Z0-9]{32})/,
  },
  {
    id: "MONGODB_CONNECTION",
    title: "MongoDB Connection String",
    description: "MongoDB connection string with credentials found in code.",
    severity: "HIGH",
    pattern: /mongodb(?:\+srv)?:\/\/[^:]+:[^@]+@[^\s'"]+/,
    allowlist: [/localhost/i, /127\.0\.0\.1/, /example\.com/i],
  },
  {
    id: "MYSQL_CONNECTION",
    title: "MySQL Connection String",
    description: "MySQL connection string with credentials found in code.",
    severity: "HIGH",
    pattern: /mysql:\/\/[^:]+:[^@]+@[^\s'"]+/,
    allowlist: [/localhost/i, /127\.0\.0\.1/, /example\.com/i],
  },
  {
    id: "GITHUB_OAUTH_CLIENT_SECRET",
    title: "GitHub OAuth Client Secret",
    description: "GitHub OAuth application secret found in code.",
    severity: "HIGH",
    pattern: /gh[os]_[A-Za-z0-9_]{36,}/,
  },
  {
    id: "GITLAB_RUNNER_TOKEN",
    title: "GitLab Runner Token",
    description: "GitLab CI runner registration token found in code.",
    severity: "HIGH",
    pattern: /(?:gitlab_runner_token|RUNNER_TOKEN)\s*[:=]\s*['"][A-Za-z0-9_-]{20,}['"]/i,
  },
  {
    id: "BITBUCKET_APP_PASSWORD",
    title: "Bitbucket App Password",
    description: "Bitbucket app password found in code.",
    severity: "HIGH",
    pattern: /(?:bitbucket_password|BITBUCKET_PASSWORD)\s*[:=]\s*['"][A-Za-z0-9]{16,}['"]/i,
  },
  {
    id: "ALGOLIA_API_KEY",
    title: "Algolia API Key",
    description: "Algolia API key found in code.",
    severity: "MEDIUM",
    pattern: /(?:algolia_api_key|ALGOLIA_API_KEY)\s*[:=]\s*['"][a-f0-9]{32}['"]/i,
  },
  {
    id: "FIREBASE_API_KEY",
    title: "Firebase API Key",
    description: "Firebase API key found in code.",
    severity: "MEDIUM",
    pattern: /(?:firebase_api_key|FIREBASE_API_KEY)\s*[:=]\s*['"][A-Za-z0-9_-]{39}['"]/i,
  },
  {
    id: "SUPABASE_API_KEY",
    title: "Supabase API Key",
    description: "Supabase API key found in code.",
    severity: "HIGH",
    pattern: /(?:supabase_key|SUPABASE_KEY)\s*[:=]\s*['"][A-Za-z0-9_-]{40,}['"]/i,
  },
  {
    id: "MAPBOX_API_KEY",
    title: "Mapbox API Key",
    description: "Mapbox API key found in code.",
    severity: "MEDIUM",
    pattern: /pk\.eyJ[A-Za-z0-9_-]{50,}/,
  },
  {
    id: "TWILIO_ACCOUNT_SID",
    title: "Twilio Account SID",
    description: "Twilio Account SID found in code.",
    severity: "HIGH",
    pattern: /AC[a-zA-Z0-9]{32}/,
  },
  {
    id: "SLACK_SIGNING_SECRET",
    title: "Slack Signing Secret",
    description: "Slack app signing secret found in code.",
    severity: "HIGH",
    pattern: /(?:slack_signing_secret|SLACK_SIGNING_SECRET)\s*[:=]\s*['"][a-f0-9]{32}['"]/i,
  },
  {
    id: "HUBSPOT_API_KEY",
    title: "HubSpot API Key",
    description: "HubSpot API key found in code.",
    severity: "HIGH",
    pattern: /(?:hubspot_api_key|HUBSPOT_API_KEY)\s*[:=]\s*['"][a-f0-9-]{36}['"]/i,
  },
  {
    id: "INTERCOM_API_KEY",
    title: "Intercom API Key",
    description: "Intercom API key found in code.",
    severity: "HIGH",
    pattern: /(?:intercom_api_key|INTERCOM_API_KEY)\s*[:=]\s*['"][a-z0-9]{20,}['"]/i,
  },
  {
    id: "NOTION_API_KEY",
    title: "Notion API Key",
    description: "Notion API key found in code.",
    severity: "HIGH",
    pattern: /(?:notion_token|NOTION_TOKEN)\s*[:=]\s*['"][a-z0-9_-]{30,}['"]/i,
  },
  {
    id: "ASANA_API_TOKEN",
    title: "Asana API Token",
    description: "Asana API token found in code.",
    severity: "HIGH",
    pattern: /(?:asana_token|ASANA_TOKEN)\s*[:=]\s*['"][a-z0-9]{20,}['"]/i,
  },
  {
    id: "JIRA_API_TOKEN",
    title: "Jira API Token",
    description: "Jira API token found in code.",
    severity: "HIGH",
    pattern: /(?:jira_api_token|JIRA_TOKEN)\s*[:=]\s*['"][A-Za-z0-9]{20,}['"]/i,
  },
  {
    id: "CONFLUENCE_API_TOKEN",
    title: "Confluence API Token",
    description: "Confluence API token found in code.",
    severity: "HIGH",
    pattern: /(?:confluence_token|CONFLUENCE_TOKEN)\s*[:=]\s*['"][A-Za-z0-9]{20,}['"]/i,
  },
  {
    id: "MAILCHIMP_API_KEY",
    title: "Mailchimp API Key",
    description: "Mailchimp API key found in code.",
    severity: "HIGH",
    pattern: /[a-f0-9]{32}-us\d+/,
  },
  {
    id: "TWITCH_API_KEY",
    title: "Twitch API Key",
    description: "Twitch API key/OAuth token found in code.",
    severity: "HIGH",
    pattern: /(?:twitch_api_key|TWITCH_OAUTH_TOKEN)\s*[:=]\s*['"][a-z0-9]{30,}['"]/i,
  },
  {
    id: "SPOTIFY_API_KEY",
    title: "Spotify API Key",
    description: "Spotify API key found in code.",
    severity: "MEDIUM",
    pattern: /(?:spotify_api_key|SPOTIFY_CLIENT_SECRET)\s*[:=]\s*['"][a-z0-9]{32}['"]/i,
  },
];
